-- Database initialization script for v0.3
-- Features:
-- 1. Internationalization support for dictionary items via JSONB (label_i18n)
-- 2. Audit status management
-- 3. Work honor/recommendation system linked to dictionary items

-- Enable UUID extension if needed (though we use BIGINT as per design)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. System Dictionary Tables
-- ==========================================

-- 1.1 System Dictionary Main Table
CREATE TABLE sys_dict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_code VARCHAR(50) NOT NULL UNIQUE, -- Dictionary Code (Unique identifier)
    dict_name VARCHAR(50) NOT NULL, -- Dictionary Name
    description VARCHAR(255), -- Description
    is_system BOOLEAN DEFAULT FALSE -- Is system preset (cannot be deleted)
);
COMMENT ON TABLE sys_dict IS 'System Dictionary Main Table';

-- 1.2 System Dictionary Item Table (v0.3: Added label_i18n, removed lang)
CREATE TABLE sys_dict_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_code VARCHAR(50) NOT NULL, -- Associated dictionary code
    item_label VARCHAR(100) NOT NULL, -- Default Display Label (Fallback)
    item_value VARCHAR(100) NOT NULL, -- Stored Value
    label_i18n JSONB, -- Multilingual Labels (e.g., {"zh-CN": "中国", "en-US": "China"})
    sort_order INTEGER DEFAULT 0, -- Sort Order
    status BOOLEAN DEFAULT TRUE, -- 1=Enabled, 0=Disabled
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_sys_dict_code FOREIGN KEY (dict_code) REFERENCES sys_dict(dict_code) ON DELETE CASCADE
);
COMMENT ON TABLE sys_dict_item IS 'System Dictionary Item Table';
COMMENT ON COLUMN sys_dict_item.label_i18n IS 'Multilingual Labels (JSONB)';

-- ==========================================
-- 2. User & Role Management
-- ==========================================

-- 2.1 System User Table
CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(50),
    clerk_id VARCHAR(255) UNIQUE, -- Clerk User ID
    password_hash VARCHAR(255), -- Password Hash (Nullable for Clerk users)
    avatar_url VARCHAR(255),
    bio TEXT,
    last_sign_in_at TIMESTAMPTZ, -- Last Sign In
    identities JSONB, -- Third-party identities
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE sys_user IS 'System User Table';

-- 2.2 System Role Table
CREATE TABLE sys_role (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(50) NOT NULL,
    description VARCHAR(255)
);
COMMENT ON TABLE sys_role IS 'System Role Table';

-- 2.3 User-Role Relation Table
CREATE TABLE sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT fk_sys_user_role_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_role_role FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE
);
COMMENT ON TABLE sys_user_role IS 'User-Role Relation Table';

-- ==========================================
-- 3. Work Management
-- ==========================================

-- 3.1 Work Base Table
CREATE TABLE work_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, -- Author ID
    title VARCHAR(255) NOT NULL, -- Title
    summary VARCHAR(255), -- Summary
    cover_url VARCHAR(255), -- Cover Image URL
    country_code VARCHAR(100), -- Country Code (Links to sys_dict_item.item_value)
    city_code VARCHAR(100), -- City Code (Links to sys_dict_item.item_value)
    category_code VARCHAR(100), -- Category Code (Links to sys_dict_item.item_value)
    dev_status_code VARCHAR(100), -- Dev Status Code (Links to sys_dict_item.item_value)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_work_base_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_base IS 'Work Base Table';

-- 3.2 Work Detail Table
CREATE TABLE work_detail (
    work_id BIGINT PRIMARY KEY, -- Work ID
    story TEXT, -- Detailed Story
    highlights JSONB, -- Key Highlights (Array)
    scenarios JSONB, -- Usage Scenarios (Array)
    demo_url VARCHAR(255), -- Demo URL
    repo_url VARCHAR(255), -- Repository URL
    CONSTRAINT fk_work_detail_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_detail IS 'Work Detail Table';

-- 3.3 Work Image Table
CREATE TABLE work_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    image_type VARCHAR(50), -- e.g., 'screenshot', 'detail'
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_work_image_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_image IS 'Work Image Table';

-- 3.4 Work Team Table
CREATE TABLE work_team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    team_intro TEXT, -- Team Introduction
    members TEXT, -- Member Names
    contact_phone VARCHAR(50),
    contact_email VARCHAR(255),
    CONSTRAINT fk_work_team_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_team IS 'Work Team Table';

-- 3.5 Work Statistic Table
CREATE TABLE work_statistic (
    work_id BIGINT PRIMARY KEY,
    audit_status INTEGER DEFAULT 0, -- 0=Pending, 1=Approved, 2=Rejected
    display_status INTEGER DEFAULT 0, -- 0=Hidden, 1=Visible
    view_count BIGINT DEFAULT 0,
    like_count BIGINT DEFAULT 0,
    last_audit_at TIMESTAMPTZ,
    CONSTRAINT fk_work_statistic_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_statistic IS 'Work Statistic Table';

-- 3.6 Work Honor Table
CREATE TABLE work_honor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    honor_item_id BIGINT NOT NULL, -- Honor Dictionary Item ID (Links to sys_dict_item.id)
    granted_at TIMESTAMPTZ DEFAULT NOW(),
    granted_by BIGINT, -- Admin ID
    CONSTRAINT fk_work_honor_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_honor_item FOREIGN KEY (honor_item_id) REFERENCES sys_dict_item(id) ON DELETE RESTRICT,
    CONSTRAINT fk_work_honor_granter FOREIGN KEY (granted_by) REFERENCES sys_user(id) ON DELETE SET NULL
);
COMMENT ON TABLE work_honor IS 'Work Honor Table';

-- 3.7 Work Audit Log Table
CREATE TABLE work_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    auditor_id BIGINT,
    prev_status INTEGER,
    new_status INTEGER,
    reason VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_work_audit_log_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_audit_log_auditor FOREIGN KEY (auditor_id) REFERENCES sys_user(id) ON DELETE SET NULL
);
COMMENT ON TABLE work_audit_log IS 'Work Audit Log Table';

-- 3.8 Work Tag Table
CREATE TABLE work_tag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_auto_audit BOOLEAN DEFAULT FALSE,
    audit_start_time TIMESTAMPTZ,
    audit_end_time TIMESTAMPTZ
);
COMMENT ON TABLE work_tag IS 'Work Tag Table';

-- 3.9 Work-Tag Relation Table
CREATE TABLE work_tag_relation (
    work_id BIGINT NOT NULL,
    tag_id INTEGER NOT NULL,
    PRIMARY KEY (work_id, tag_id),
    CONSTRAINT fk_work_tag_rel_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_tag_rel_tag FOREIGN KEY (tag_id) REFERENCES work_tag(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_tag_relation IS 'Work-Tag Relation Table';

-- 3.10 Work Like Table
CREATE TABLE work_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uk_work_like_user_work UNIQUE (user_id, work_id),
    CONSTRAINT fk_work_like_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_like_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_like IS 'Work Like Table';

-- Indexes
CREATE INDEX idx_work_base_user_id ON work_base(user_id);
CREATE INDEX idx_work_base_country_code ON work_base(country_code);
CREATE INDEX idx_work_base_city_code ON work_base(city_code);
CREATE INDEX idx_work_base_category_code ON work_base(category_code);
CREATE INDEX idx_work_image_work_id ON work_image(work_id);
CREATE INDEX idx_work_team_work_id ON work_team(work_id);
CREATE INDEX idx_work_honor_work_id ON work_honor(work_id);
CREATE INDEX idx_work_audit_log_work_id ON work_audit_log(work_id);
CREATE INDEX idx_work_like_work_id ON work_like(work_id);
CREATE INDEX idx_work_like_user_id ON work_like(user_id);


-- ==========================================
-- 4. Initial Data Seeding (v0.3)
-- ==========================================

-- 4.1 Seed System Dictionaries
INSERT INTO sys_dict (dict_code, dict_name, description, is_system) VALUES
('audit_status', 'Audit Status', 'Status of work audit process', true),
('dev_status', 'Development Status', 'Current stage of development', true),
('project_category', 'Project Category', 'Category of the project', true),
('country', 'Country', 'Country list', true),
('city', 'City', 'City list', true),
('honor_type', 'Honor Type', 'Types of honors awarded to works', true);

-- 4.2 Seed System Dictionary Items (with label_i18n)

-- Audit Status
INSERT INTO sys_dict_item (dict_code, item_label, item_value, label_i18n, sort_order) VALUES
('audit_status', '待审核', '0', '{"zh-CN": "待审核", "en-US": "Pending"}', 0),
('audit_status', '已通过', '1', '{"zh-CN": "已通过", "en-US": "Approved"}', 1),
('audit_status', '已拒绝', '2', '{"zh-CN": "已拒绝", "en-US": "Rejected"}', 2);

-- Development Status
INSERT INTO sys_dict_item (dict_code, item_label, item_value, label_i18n, sort_order) VALUES
('dev_status', '创意构思', 'ideation', '{"zh-CN": "创意构思", "en-US": "Ideation"}', 0),
('dev_status', '原型设计', 'prototype', '{"zh-CN": "原型设计", "en-US": "Prototype"}', 1),
('dev_status', '开发中', 'development', '{"zh-CN": "开发中", "en-US": "In Development"}', 2),
('dev_status', '已上线', 'released', '{"zh-CN": "已上线", "en-US": "Released"}', 3);

-- Project Category
INSERT INTO sys_dict_item (dict_code, item_label, item_value, label_i18n, sort_order) VALUES
('project_category', '游戏', 'game', '{"zh-CN": "游戏", "en-US": "Game"}', 0),
('project_category', '工具', 'tool', '{"zh-CN": "工具", "en-US": "Tool"}', 1),
('project_category', 'AI应用', 'ai', '{"zh-CN": "AI应用", "en-US": "AI App"}', 2),
('project_category', '社交', 'social', '{"zh-CN": "社交", "en-US": "Social"}', 3),
('project_category', '教育', 'education', '{"zh-CN": "教育", "en-US": "Education"}', 4);

-- Country (Sample)
INSERT INTO sys_dict_item (dict_code, item_label, item_value, label_i18n, sort_order) VALUES
('country', '中国', 'CN', '{"zh-CN": "中国", "en-US": "China"}', 0),
('country', '美国', 'US', '{"zh-CN": "美国", "en-US": "USA"}', 1),
('country', '日本', 'JP', '{"zh-CN": "日本", "en-US": "Japan"}', 2);

-- City (Sample)
INSERT INTO sys_dict_item (dict_code, item_label, item_value, label_i18n, sort_order) VALUES
('city', '北京', '110100', '{"zh-CN": "北京", "en-US": "Beijing"}', 0),
('city', '上海', '310100', '{"zh-CN": "上海", "en-US": "Shanghai"}', 1),
('city', '深圳', '440300', '{"zh-CN": "深圳", "en-US": "Shenzhen"}', 2),
('city', '杭州', '330100', '{"zh-CN": "杭州", "en-US": "Hangzhou"}', 3);

-- Honor Type (Sample)
INSERT INTO sys_dict_item (dict_code, item_label, item_value, label_i18n, sort_order) VALUES
('honor_type', '社区推荐', 'community_choice', '{"zh-CN": "社区推荐", "en-US": "Community Choice"}', 0),
('honor_type', '城市之星', 'city_star', '{"zh-CN": "城市之星", "en-US": "City Star"}', 1),
('honor_type', '年度最佳', 'best_of_year', '{"zh-CN": "年度最佳", "en-US": "Best of Year"}', 2);
