BEGIN;

CREATE TABLE IF NOT EXISTS sys_auth_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    clerk_id VARCHAR(255),
    auth_type VARCHAR(50) NOT NULL,
    auth_channel VARCHAR(50),
    auth_status VARCHAR(20) NOT NULL DEFAULT 'success',
    ip_address VARCHAR(64),
    user_agent VARCHAR(512),
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_sys_auth_log_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_sys_auth_log_user_id ON sys_auth_log(user_id);
CREATE INDEX IF NOT EXISTS idx_sys_auth_log_clerk_id ON sys_auth_log(clerk_id);
CREATE INDEX IF NOT EXISTS idx_sys_auth_log_auth_type ON sys_auth_log(auth_type);
CREATE INDEX IF NOT EXISTS idx_sys_auth_log_created_at ON sys_auth_log(created_at DESC);

CREATE TABLE IF NOT EXISTS sys_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT,
    module VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    target_type VARCHAR(50),
    target_id VARCHAR(255),
    success BOOLEAN NOT NULL DEFAULT TRUE,
    error_message VARCHAR(500),
    request_method VARCHAR(16),
    request_path VARCHAR(255),
    ip_address VARCHAR(64),
    user_agent VARCHAR(512),
    payload JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_sys_operation_log_operator FOREIGN KEY (operator_id) REFERENCES sys_user(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_sys_operation_log_operator_id ON sys_operation_log(operator_id);
CREATE INDEX IF NOT EXISTS idx_sys_operation_log_module_action ON sys_operation_log(module, action);
CREATE INDEX IF NOT EXISTS idx_sys_operation_log_created_at ON sys_operation_log(created_at DESC);

COMMIT;
