-- Enable UUID extension if needed (though we use BIGINT as per design)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. 系统字典主表 (sys_dict)
-- 管理系统中的枚举值类型 (如: 城市, 国家, 作品类别)
CREATE TABLE sys_dict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_code VARCHAR(50) NOT NULL UNIQUE, -- 字典编码 (Unique)
    dict_name VARCHAR(50) NOT NULL, -- 字典名称
    description VARCHAR(255), -- 描述信息
    is_system BOOLEAN DEFAULT FALSE -- 是否系统预设 (不可删)
);
COMMENT ON TABLE sys_dict IS '系统字典主表: 管理系统中的枚举值类型';
COMMENT ON COLUMN sys_dict.dict_code IS '字典编码 (Unique)';
COMMENT ON COLUMN sys_dict.dict_name IS '字典名称';
COMMENT ON COLUMN sys_dict.is_system IS '是否系统预设 (不可删)';

-- 2. 系统字典项表 (sys_dict_item)
-- 具体的字典值 (如: 北京, 上海)
CREATE TABLE sys_dict_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_code VARCHAR(50) NOT NULL, -- 关联的字典编码
    item_label VARCHAR(100) NOT NULL, -- 显示标签
    lang VARCHAR(20) DEFAULT 'zh-CN', -- 语言标识 (e.g., zh-CN, en-US, ja-JP)
    item_value VARCHAR(100) NOT NULL, -- 存储值
    sort_order INTEGER DEFAULT 0, -- 排序字段
    status BOOLEAN DEFAULT TRUE, -- 1=启用, 0=禁用
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_sys_dict_code FOREIGN KEY (dict_code) REFERENCES sys_dict(dict_code) ON DELETE CASCADE
);
COMMENT ON TABLE sys_dict_item IS '系统字典项表';
COMMENT ON COLUMN sys_dict_item.item_label IS '显示标签';
COMMENT ON COLUMN sys_dict_item.item_value IS '存储值';

-- 3. 系统用户表 (sys_user)
-- 存储用户的基本登录和个人信息
CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL, -- 用户名
    email VARCHAR(255) NOT NULL UNIQUE, -- 邮箱
    phone VARCHAR(50), -- 电话号码
    password_hash VARCHAR(255) NOT NULL, -- 密码哈希
    avatar_url VARCHAR(255), -- 头像地址
    bio TEXT, -- 个人简介
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE sys_user IS '系统用户表';

-- 4. 系统角色表 (sys_role)
-- 定义用户权限角色
CREATE TABLE sys_role (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE, -- 角色编码
    role_name VARCHAR(50) NOT NULL, -- 角色名称
    description VARCHAR(255)
);
COMMENT ON TABLE sys_role IS '系统角色表';

-- 5. 用户角色关联表 (sys_user_role)
CREATE TABLE sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT fk_sys_user_role_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_role_role FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE
);
COMMENT ON TABLE sys_user_role IS '用户角色关联表';

-- 6. 作品基础表 (work_base)
-- 存储作品的核心元数据 (列表展示用)
CREATE TABLE work_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, -- 作者ID
    title VARCHAR(255) NOT NULL, -- 作品标题
    summary VARCHAR(255), -- 作品摘要
    cover_url VARCHAR(255), -- 封面图片地址
    country_code VARCHAR(100), -- 国家编码
    city_code VARCHAR(100), -- 城市编码
    category_code VARCHAR(100), -- 作品类别编码
    dev_status_code VARCHAR(100), -- 开发状态编码
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_work_base_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_base IS '作品基础表';

-- 7. 作品详情表 (work_detail)
-- 存储作品的详细内容 (垂直分表)
CREATE TABLE work_detail (
    work_id BIGINT PRIMARY KEY, -- 作品ID
    story TEXT, -- 详细故事/介绍
    highlights JSONB, -- 核心亮点 (数组)
    scenarios JSONB, -- 使用场景 (数组)
    demo_url VARCHAR(255), -- 演示链接
    repo_url VARCHAR(255), -- 代码仓库链接
    CONSTRAINT fk_work_detail_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_detail IS '作品详情表';

-- 8. 作品图片表 (work_image)
-- 存储作品的多张展示图片
CREATE TABLE work_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL, -- 图片地址
    image_type VARCHAR(50), -- 图片类型
    sort_order INTEGER DEFAULT 0, -- 排序字段
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_work_image_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_image IS '作品图片表';

-- 9. 团队信息表 (work_team)
-- 存储作品的团队成员和联系方式
CREATE TABLE work_team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    team_intro TEXT, -- 团队介绍
    members TEXT, -- 成员名单
    contact_phone VARCHAR(50), -- 联系电话
    contact_email VARCHAR(255), -- 联系邮箱
    CONSTRAINT fk_work_team_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_team IS '团队信息表';

-- 10. 作品状态与统计表 (work_statistic)
-- 存储高频变动的统计数据和状态
CREATE TABLE work_statistic (
    work_id BIGINT PRIMARY KEY,
    audit_status INTEGER DEFAULT 0, -- 0=待审, 1=通过, 2=拒绝
    display_status INTEGER DEFAULT 0, -- 0=下架, 1=上架
    view_count BIGINT DEFAULT 0, -- 浏览量
    like_count BIGINT DEFAULT 0, -- 点赞量
    last_audit_at TIMESTAMPTZ, -- 最后审核时间
    CONSTRAINT fk_work_statistic_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_statistic IS '作品状态与统计表';

-- 11. 作品荣誉/推荐表 (work_honor)
-- 存储作品获得的荣誉或推荐
CREATE TABLE work_honor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    honor_item_id BIGINT NOT NULL, -- 荣誉字典项ID (关联 sys_dict_item.id)
    granted_at TIMESTAMPTZ DEFAULT NOW(), -- 授予时间
    granted_by BIGINT, -- 授予人ID
    CONSTRAINT fk_work_honor_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_honor_item FOREIGN KEY (honor_item_id) REFERENCES sys_dict_item(id) ON DELETE RESTRICT,
    CONSTRAINT fk_work_honor_granter FOREIGN KEY (granted_by) REFERENCES sys_user(id) ON DELETE SET NULL
);
COMMENT ON TABLE work_honor IS '作品荣誉/推荐表';

-- 12. 审核记录表 (work_audit_log)
-- 记录作品的审核历史
CREATE TABLE work_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    auditor_id BIGINT, -- 审核人ID
    prev_status INTEGER, -- 原状态
    new_status INTEGER, -- 新状态
    reason VARCHAR(255), -- 审核原因
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_work_audit_log_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_audit_log_auditor FOREIGN KEY (auditor_id) REFERENCES sys_user(id) ON DELETE SET NULL
);
COMMENT ON TABLE work_audit_log IS '审核记录表';

-- 13. 作品标签表 (work_tag)
-- 存储系统标签或活动标签
CREATE TABLE work_tag (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE, -- 标签名称
    is_auto_audit BOOLEAN DEFAULT FALSE, -- 是否自动过审
    audit_start_time TIMESTAMPTZ, -- 自动过审开始时间
    audit_end_time TIMESTAMPTZ -- 自动过审结束时间
);
COMMENT ON TABLE work_tag IS '作品标签表';

-- 14. 作品-标签关联表 (work_tag_relation)
CREATE TABLE work_tag_relation (
    work_id BIGINT NOT NULL,
    tag_id INTEGER NOT NULL,
    PRIMARY KEY (work_id, tag_id),
    CONSTRAINT fk_work_tag_rel_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_tag_rel_tag FOREIGN KEY (tag_id) REFERENCES work_tag(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_tag_relation IS '作品-标签关联表';

-- 15. 作品点赞记录表 (work_like)
CREATE TABLE work_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uk_work_like_user_work UNIQUE (user_id, work_id),
    CONSTRAINT fk_work_like_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_like_work FOREIGN KEY (work_id) REFERENCES work_base(id) ON DELETE CASCADE
);
COMMENT ON TABLE work_like IS '作品点赞记录表';

-- Indexes for performance
CREATE INDEX idx_work_base_user_id ON work_base(user_id);
CREATE INDEX idx_work_base_country_code ON work_base(country_code);
CREATE INDEX idx_work_base_city_code ON work_base(city_code);
CREATE INDEX idx_work_base_category_code ON work_base(category_code);
CREATE INDEX idx_work_image_work_id ON work_image(work_id);
CREATE INDEX idx_work_team_work_id ON work_team(work_id);
CREATE INDEX idx_work_honor_work_id ON work_honor(work_id);
CREATE INDEX idx_work_audit_log_work_id ON work_audit_log(work_id);
CREATE INDEX idx_work_like_work_id ON work_like(work_id);
CREATE INDEX idx_work_like_user_id ON work_like(user_id);
